// Generated by CoffeeScript 1.6.3
var bindTabs, displayPosts, fetchPosts, fetchTest, foo;

foo = null;

fetchTest = function() {
  return $.ajax({
    type: "POST",
    url: 'php/test.php',
    data: {
      "foo": "narf"
    },
    success: function(data) {
      return console.log(data);
    }
  });
};

fetchPosts = function(query) {
  return $.ajax({
    type: "POST",
    url: 'php/retrievePosts.php',
    data: {
      "subreddit": query.subreddit,
      "sort": query.sort
    },
    success: function(data) {
      return displayPosts(data);
    },
    dataType: 'json'
  });
};

displayPosts = function(data) {
  var downvote, post, row, subreddit, title, type, upvote, url, username, _i, _len, _results;
  console.log("displayAll called");
  _results = [];
  for (_i = 0, _len = data.length; _i < _len; _i++) {
    post = data[_i];
    title = post['title'];
    url = post['url'];
    subreddit = post['subreddit'];
    upvote = post['upvote'];
    downvote = post['downvote'];
    type = post['type'];
    username = post['username'];
    row = null;
    if (type === "1") {
      row = "<div class='row postrow'>		            <div class='col-md-10 col-lg-10 col-xs-10 reddit-link'>		                <a href='" + url + "'>" + title + "</a>		                <div></div>		                <div class='details submission'>submitted by <a href='reddit.com/u/user'>" + username + "</a> to <a href='reddit.com/r/subreddit'>" + subreddit + "</a>		                </div>		                <div class='details comments'>109234 comments -></div>		            </div>		            <div class='col-md-2 col-lg-2 col-xs-2 '>		                <div class='vote'>		                    <span class='glyphicon glyphicon-arrow-up arrow'></span>		                    <span class='count'>" + (upvote - downvote) + " </span>		                    <span class='glyphicon glyphicon-arrow-down arrow'></span>		                </div>		            </div>		        </div>";
    } else if (type === '2') {
      row = "<div class='row postrow'>		            <div class='col-md-10 col-lg-10 col-xs-10 reddit-link'>" + title + "<div></div>		                <div class='details submission'>submitted by <a href='reddit.com/u/user'>" + username + "</a> to <a href='reddit.com/r/subreddit'>" + subreddit + "</a>		                </div>		                <div class='details comments'>109234 comments -></div>		            </div>		            <div class='col-md-2 col-lg-2 col-xs-2 '>		                <div class='vote'>		                    <span class='glyphicon glyphicon-arrow-up arrow'></span>		                    <span class='count'>" + (upvote - downvote) + " </span>		                    <span class='glyphicon glyphicon-arrow-down arrow'></span>		                </div>		            </div>		        </div>";
    }
    _results.push($('#todo-row').after(row));
  }
  return _results;
};

bindTabs = function() {
  console.log('bindTabs called');
  $('#hot').click(function() {
    return $(".postrow").fadeOut(300, function() {
      $(".postrow").remove();
      return fetchPosts({
        sort: "top",
        subreddit: "all"
      });
    });
  });
  $('#new').click(function() {
    return $(".postrow").fadeOut(300, function() {
      $(".postrow").remove();
      return fetchPosts({
        sort: "new",
        subreddit: "all"
      });
    });
  });
  $('#controversial').click(function() {
    return $(".postrow").fadeOut(300, function() {
      $(".postrow").remove();
      return fetchPosts({
        sort: "controversial",
        subreddit: "all"
      });
    });
  });
  return $('#top').click(function() {
    return $(".postrow").fadeOut(300, function() {
      $(".postrow").remove();
      return fetchPosts({
        sort: "top",
        subreddit: "all"
      });
    });
  });
};

$(document).ready(function() {
  console.log("working");
  fetchPosts({
    sort: "top",
    subreddit: "all"
  });
  return bindTabs();
});
